"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { Song } from "@/types";
import { useFirestore, addDocumentNonBlocking } from "@/firebase";
import { collection, serverTimestamp } from "firebase/firestore";
import { useToast } from "@/hooks/use-toast";

type UploadSongDialogProps = {
  isOpen: boolean;
  setIsOpen: (open: boolean) => void;
  userId: string;
};

export function UploadSongDialog({ isOpen, setIsOpen, userId }: UploadSongDialogProps) {
  const firestore = useFirestore();
  const { toast } = useToast();
  const [title, setTitle] = useState("");
  const [artist, setArtist] = useState("");
  const [album, setAlbum] = useState("");
  const [albumArt, setAlbumArt] = useState<File | null>(null);
  const [audioSrc, setAudioSrc] = useState<File | null>(null);
  const [isUploading, setIsUploading] = useState(false);

  const handleSubmit = async () => {
    if (!title || !artist || !album || !albumArt || !audioSrc) {
      toast({
        title: "Missing Information",
        description: "Please fill out all fields and select both files.",
        variant: "destructive",
      });
      return;
    }

    setIsUploading(true);

    // Note: In a real app, you'd upload files to a service like Firebase Storage
    // and get back URLs. Here, we're still using local object URLs.
    // The song METADATA will be saved to Firestore.
    const newSong = {
      // id is generated by firestore
      title,
      artist,
      album,
      albumArt: URL.createObjectURL(albumArt),
      audioSrc: URL.createObjectURL(audioSrc),
      liked: false,
      dateAdded: serverTimestamp(),
      playCount: 0,
    };

    try {
      const songsCollection = collection(firestore, `users/${userId}/songs`);
      await addDocumentNonBlocking(songsCollection, newSong);

      toast({
        title: "Song Uploaded!",
        description: `${title} has been added to your library.`,
      });
      
      setIsOpen(false);
      // Reset form
      setTitle("");
      setArtist("");
      setAlbum("");
      setAlbumArt(null);
      setAudioSrc(null);
    } catch (error) {
      console.error("Error uploading song:", error);
      toast({
        title: "Upload Failed",
        description: "There was an error saving your song. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsUploading(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Upload Song</DialogTitle>
          <DialogDescription>
            Add a new song to your library. Fill in the details below.
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="title" className="text-right">
              Title
            </Label>
            <Input
              id="title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="col-span-3"
              disabled={isUploading}
            />
          </div>
          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="artist" className="text-right">
              Artist
            </Label>
            <Input
              id="artist"
              value={artist}
              onChange={(e) => setArtist(e.target.value)}
              className="col-span-3"
              disabled={isUploading}
            />
          </div>
          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="album" className="text-right">
              Album
            </Label>
            <Input
              id="album"
              value={album}
              onChange={(e) => setAlbum(e.target.value)}
              className="col-span-3"
              disabled={isUploading}
            />
          </div>
          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="album-art" className="text-right">
              Album Art
            </Label>
            <Input
              id="album-art"
              type="file"
              accept="image/*"
              onChange={(e) => setAlbumArt(e.target.files?.[0] || null)}
              className="col-span-3"
              disabled={isUploading}
            />
          </div>
          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="audio-file" className="text-right">
              Audio File
            </Label>
            <Input
              id="audio-file"
              type="file"
              accept="audio/*"
              onChange={(e) => setAudioSrc(e.target.files?.[0] || null)}
              className="col-span-3"
              disabled={isUploading}
            />
          </div>
        </div>
        <DialogFooter>
          <Button type="submit" onClick={handleSubmit} disabled={isUploading}>
            {isUploading ? "Uploading..." : "Upload"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
